//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passtable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Passtable.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string bt_abort {
            get {
                return ResourceManager.GetString("bt_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string bt_about {
            get {
                return ResourceManager.GetString("bt_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_aboutLogPass_tip {
            get {
                return ResourceManager.GetString("bt_aboutLogPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string bt_add {
            get {
                return ResourceManager.GetString("bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an entry to the table (Ctrl+N).
        /// </summary>
        public static string bt_add_tip {
            get {
                return ResourceManager.GetString("bt_add_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string bt_close {
            get {
                return ResourceManager.GetString("bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table.
        /// </summary>
        public static string bt_createTable {
            get {
                return ResourceManager.GetString("bt_createTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new table (Ctrl+N).
        /// </summary>
        public static string bt_createTable_tip {
            get {
                return ResourceManager.GetString("bt_createTable_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string bt_delete {
            get {
                return ResourceManager.GetString("bt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry from the table (Del).
        /// </summary>
        public static string bt_delete_tip {
            get {
                return ResourceManager.GetString("bt_delete_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from app site.
        /// </summary>
        public static string bt_downloadNewVersion {
            get {
                return ResourceManager.GetString("bt_downloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string bt_edit {
            get {
                return ResourceManager.GetString("bt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data in the entry (Ctrl+E).
        /// </summary>
        public static string bt_edit_tip {
            get {
                return ResourceManager.GetString("bt_edit_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string bt_enter {
            get {
                return ResourceManager.GetString("bt_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string bt_license {
            get {
                return ResourceManager.GetString("bt_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_logPass {
            get {
                return ResourceManager.GetString("bt_logPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically copy username, then password (Ctrl+D).
        /// </summary>
        public static string bt_logPass_tip {
            get {
                return ResourceManager.GetString("bt_logPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string bt_reportProblem {
            get {
                return ResourceManager.GetString("bt_reportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string bt_save {
            get {
                return ResourceManager.GetString("bt_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save with current password.
        /// </summary>
        public static string bt_saveWithCurrentPassword {
            get {
                return ResourceManager.GetString("bt_saveWithCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string bt_search {
            get {
                return ResourceManager.GetString("bt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the table by notes and usernames (Ctrl+F).
        /// </summary>
        public static string bt_search_tip {
            get {
                return ResourceManager.GetString("bt_search_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support developer.
        /// </summary>
        public static string bt_supportDeveloper {
            get {
                return ResourceManager.GetString("bt_supportDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party resources.
        /// </summary>
        public static string bt_thirdPartyResources {
            get {
                return ResourceManager.GetString("bt_thirdPartyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string edit_confirm {
            get {
                return ResourceManager.GetString("edit_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to skip.
        /// </summary>
        public static string edit_leaveBlankToSkip {
            get {
                return ResourceManager.GetString("edit_leaveBlankToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary password.
        /// </summary>
        public static string edit_primaryPassword {
            get {
                return ResourceManager.GetString("edit_primaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged..
        /// </summary>
        public static string err_critical_fileDamaged {
            get {
                return ResourceManager.GetString("err_critical_fileDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not supported..
        /// </summary>
        public static string err_critical_fileNotSupported {
            get {
                return ResourceManager.GetString("err_critical_fileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error.
        /// </summary>
        public static string err_critical_title {
            get {
                return ResourceManager.GetString("err_critical_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file was created in a later version of the app and cannot be opened. Update the app..
        /// </summary>
        public static string err_critical_updateApp {
            get {
                return ResourceManager.GetString("err_critical_updateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data contains invalid characters..
        /// </summary>
        public static string err_edit_dataInvalidChars {
            get {
                return ResourceManager.GetString("err_edit_dataInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry must contain note or username with password..
        /// </summary>
        public static string err_edit_itemMustContain {
            get {
                return ResourceManager.GetString("err_edit_itemMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        public static string err_edit_passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("err_edit_passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error is probably caused by using an unsupported character..
        /// </summary>
        public static string err_encryption_msg {
            get {
                return ResourceManager.GetString("err_encryption_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption error.
        /// </summary>
        public static string err_encryption_title {
            get {
                return ResourceManager.GetString("err_encryption_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name is not supported..
        /// </summary>
        public static string err_fileName_invalid {
            get {
                return ResourceManager.GetString("err_fileName_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not start with a space character..
        /// </summary>
        public static string err_fileName_spaceChar {
            get {
                return ResourceManager.GetString("err_fileName_spaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is too long..
        /// </summary>
        public static string err_fileName_tooLong {
            get {
                return ResourceManager.GetString("err_fileName_tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Log&apos;n&apos;Pass system is currently unavailable..
        /// </summary>
        public static string err_logPass_msg {
            get {
                return ResourceManager.GetString("err_logPass_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file..
        /// </summary>
        public static string err_openFileFail {
            get {
                return ResourceManager.GetString("err_openFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary password cannot be empty..
        /// </summary>
        public static string err_primaryPassword_empty {
            get {
                return ResourceManager.GetString("err_primaryPassword_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string err_primaryPassword_incorrect {
            get {
                return ResourceManager.GetString("err_primaryPassword_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary password contains invalid characters. Allowed characters: .
        /// </summary>
        public static string err_primaryPassword_invalidChars {
            get {
                return ResourceManager.GetString("err_primaryPassword_invalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary password cannot start with a forward slash..
        /// </summary>
        public static string err_primaryPassword_slashChar {
            get {
                return ResourceManager.GetString("err_primaryPassword_slashChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary password is too long (max. 32 chars)..
        /// </summary>
        public static string err_primaryPassword_tooLong {
            get {
                return ResourceManager.GetString("err_primaryPassword_tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string err_title {
            get {
                return ResourceManager.GetString("err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application does not have sufficient permissions to write data to this file. You need to save the data via &quot;Save as&quot; to a new file to avoid losing data..
        /// </summary>
        public static string err_write_msg {
            get {
                return ResourceManager.GetString("err_write_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write error.
        /// </summary>
        public static string err_write_title {
            get {
                return ResourceManager.GetString("err_write_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Max Korolev.
        /// </summary>
        public static string info_createdBy {
            get {
                return ResourceManager.GetString("info_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Copyright 2023 Maxim Korolev
        ///    Licensed under the Apache License, Version 2.0
        ///    
        ///    
        ///                                 Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string info_license {
            get {
                return ResourceManager.GetString("info_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • The system only works with entries that contain username and password.
        ///• The system does not work in the Passtable app.
        ///• At the end of the work, the clipboard will be cleared..
        /// </summary>
        public static string info_logPass_notes {
            get {
                return ResourceManager.GetString("info_logPass_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select an entry in the table;
        ///2. Click on the &quot;Log&apos;n&apos;pass&quot; button (Ctrl+D);
        ///3. Go to authorization form (for example: authorization on the website in the browser, credentials entry in the mail client);
        ///4. Select the &quot;username&quot; field and press Ctrl+V;
        ///5. Then select the &quot;password&quot; field and press Ctrl+V;
        ///6. Done..
        /// </summary>
        public static string info_logPass_steps {
            get {
                return ResourceManager.GetString("info_logPass_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use &quot;Log&apos;n&apos;pass&quot; system.
        /// </summary>
        public static string info_logPass_title {
            get {
                return ResourceManager.GetString("info_logPass_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project page:.
        /// </summary>
        public static string info_projectPage {
            get {
                return ResourceManager.GetString("info_projectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project repo:.
        /// </summary>
        public static string info_projectRepo {
            get {
                return ResourceManager.GetString("info_projectRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///HandyControls
        ///Mahdi Hosseini
        ///https://ghost1372.github.io/handycontrol/
        ///based on HandyControl
        ///HandyOrg
        ///MIT License
        ///https://handyorg.github.io/
        ///
        ///Costura.Fody
        ///Fody
        ///MIT license
        ///
        ///Resource.Embedder
        ///Marc Stan
        ///MIT license
        ///
        ///Fluent Emoji
        ///Microsoft Corporation
        ///MIT license
        ///
        ///Material Design icons 
        ///Google LLC
        ///Apache License 2.0
        ///https://fonts.google.com/icons
        ///
        ///Newtonsoft.Json
        ///James Newton-King
        ///https://www.newtonsoft.com/json
        ///.
        /// </summary>
        public static string info_thirdPartyResources {
            get {
                return ResourceManager.GetString("info_thirdPartyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update contains improvements and bug fixes.
        /// </summary>
        public static string info_updateAvailable {
            get {
                return ResourceManager.GetString("info_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for Windows.
        /// </summary>
        public static string info_winApp {
            get {
                return ResourceManager.GetString("info_winApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space.
        /// </summary>
        public static string key_space {
            get {
                return ResourceManager.GetString("key_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is permanent and cannot be undone.
        /// </summary>
        public static string msg_permanentAction {
            get {
                return ResourceManager.GetString("msg_permanentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string title_about {
            get {
                return ResourceManager.GetString("title_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entry.
        /// </summary>
        public static string title_addEntry {
            get {
                return ResourceManager.GetString("title_addEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file.
        /// </summary>
        public static string title_createNewFile {
            get {
                return ResourceManager.GetString("title_createNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry?.
        /// </summary>
        public static string title_deleteEntry {
            get {
                return ResourceManager.GetString("title_deleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        public static string title_editEntry {
            get {
                return ResourceManager.GetString("title_editEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string title_note {
            get {
                return ResourceManager.GetString("title_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string title_openFile {
            get {
                return ResourceManager.GetString("title_openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string title_password {
            get {
                return ResourceManager.GetString("title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string title_saveAs {
            get {
                return ResourceManager.GetString("title_saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string title_tag {
            get {
                return ResourceManager.GetString("title_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string title_updateAvailable {
            get {
                return ResourceManager.GetString("title_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string title_username {
            get {
                return ResourceManager.GetString("title_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string toolbar_help {
            get {
                return ResourceManager.GetString("toolbar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts and information about the app (F1).
        /// </summary>
        public static string toolbar_help_tip {
            get {
                return ResourceManager.GetString("toolbar_help_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string toolbar_new {
            get {
                return ResourceManager.GetString("toolbar_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file (Ctrl+Shift+N).
        /// </summary>
        public static string toolbar_new_tip {
            get {
                return ResourceManager.GetString("toolbar_new_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string toolbar_open {
            get {
                return ResourceManager.GetString("toolbar_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file (Ctrl+O).
        /// </summary>
        public static string toolbar_open_tip {
            get {
                return ResourceManager.GetString("toolbar_open_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string toolbar_saveAs {
            get {
                return ResourceManager.GetString("toolbar_saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to another file with primary password change (Ctrl+Shift+S).
        /// </summary>
        public static string toolbar_saveAs_tip {
            get {
                return ResourceManager.GetString("toolbar_saveAs_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string toolbar_status_copied {
            get {
                return ResourceManager.GetString("toolbar_status_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data.
        /// </summary>
        public static string toolbar_status_notEnoughData {
            get {
                return ResourceManager.GetString("toolbar_status_notEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string toolbar_status_nothingSelected {
            get {
                return ResourceManager.GetString("toolbar_status_nothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string toolbar_status_saved {
            get {
                return ResourceManager.GetString("toolbar_status_saved", resourceCulture);
            }
        }
    }
}
