//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passtable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Passtable.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string bt_abort {
            get {
                return ResourceManager.GetString("bt_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_aboutLogPass_tip {
            get {
                return ResourceManager.GetString("bt_aboutLogPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string bt_add {
            get {
                return ResourceManager.GetString("bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an entry to the table (Ctrl+N).
        /// </summary>
        public static string bt_add_tip {
            get {
                return ResourceManager.GetString("bt_add_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string bt_close {
            get {
                return ResourceManager.GetString("bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table.
        /// </summary>
        public static string bt_createTable {
            get {
                return ResourceManager.GetString("bt_createTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new table (Ctrl+N).
        /// </summary>
        public static string bt_createTable_tip {
            get {
                return ResourceManager.GetString("bt_createTable_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string bt_delete {
            get {
                return ResourceManager.GetString("bt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry from the table (Del).
        /// </summary>
        public static string bt_delete_tip {
            get {
                return ResourceManager.GetString("bt_delete_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string bt_edit {
            get {
                return ResourceManager.GetString("bt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data in the entry (Ctrl+E).
        /// </summary>
        public static string bt_edit_tip {
            get {
                return ResourceManager.GetString("bt_edit_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_logPass {
            get {
                return ResourceManager.GetString("bt_logPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically copy username, then password (Ctrl+D).
        /// </summary>
        public static string bt_logPass_tip {
            get {
                return ResourceManager.GetString("bt_logPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string bt_search {
            get {
                return ResourceManager.GetString("bt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the table by notes and usernames (Ctrl+F).
        /// </summary>
        public static string bt_search_tip {
            get {
                return ResourceManager.GetString("bt_search_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string title_note {
            get {
                return ResourceManager.GetString("title_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string title_password {
            get {
                return ResourceManager.GetString("title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string title_tag {
            get {
                return ResourceManager.GetString("title_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string title_username {
            get {
                return ResourceManager.GetString("title_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string toolbar_help {
            get {
                return ResourceManager.GetString("toolbar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts and information about the app (F1).
        /// </summary>
        public static string toolbar_help_tip {
            get {
                return ResourceManager.GetString("toolbar_help_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string toolbar_new {
            get {
                return ResourceManager.GetString("toolbar_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file (Ctrl+Shift+N).
        /// </summary>
        public static string toolbar_new_tip {
            get {
                return ResourceManager.GetString("toolbar_new_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string toolbar_open {
            get {
                return ResourceManager.GetString("toolbar_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file (Ctrl+O).
        /// </summary>
        public static string toolbar_open_tip {
            get {
                return ResourceManager.GetString("toolbar_open_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string toolbar_saveAs {
            get {
                return ResourceManager.GetString("toolbar_saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to another file with primary password change (Ctrl+Shift+S).
        /// </summary>
        public static string toolbar_saveAs_tip {
            get {
                return ResourceManager.GetString("toolbar_saveAs_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string toolbar_status_nothingSelected {
            get {
                return ResourceManager.GetString("toolbar_status_nothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string toolbar_status_saved {
            get {
                return ResourceManager.GetString("toolbar_status_saved", resourceCulture);
            }
        }
    }
}
