//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passtable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_ru_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings_ru_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Passtable.Resources.Strings.ru-ru", typeof(Strings_ru_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать.
        /// </summary>
        public static string bt_abort {
            get {
                return ResourceManager.GetString("bt_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О приложении.
        /// </summary>
        public static string bt_about {
            get {
                return ResourceManager.GetString("bt_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее о Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_aboutLogPass_tip {
            get {
                return ResourceManager.GetString("bt_aboutLogPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string bt_add {
            get {
                return ResourceManager.GetString("bt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись в таблицу (Ctrl+N).
        /// </summary>
        public static string bt_add_tip {
            get {
                return ResourceManager.GetString("bt_add_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string bt_close {
            get {
                return ResourceManager.GetString("bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать таблицу.
        /// </summary>
        public static string bt_createTable {
            get {
                return ResourceManager.GetString("bt_createTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую таблицу (Ctrl+N).
        /// </summary>
        public static string bt_createTable_tip {
            get {
                return ResourceManager.GetString("bt_createTable_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string bt_delete {
            get {
                return ResourceManager.GetString("bt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись из таблицы (Del).
        /// </summary>
        public static string bt_delete_tip {
            get {
                return ResourceManager.GetString("bt_delete_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить с сайта приложения.
        /// </summary>
        public static string bt_downloadNewVersion {
            get {
                return ResourceManager.GetString("bt_downloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string bt_edit {
            get {
                return ResourceManager.GetString("bt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить данные в записи (Ctrl+E).
        /// </summary>
        public static string bt_edit_tip {
            get {
                return ResourceManager.GetString("bt_edit_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод.
        /// </summary>
        public static string bt_enter {
            get {
                return ResourceManager.GetString("bt_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия.
        /// </summary>
        public static string bt_license {
            get {
                return ResourceManager.GetString("bt_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log&apos;n&apos;Pass.
        /// </summary>
        public static string bt_logPass {
            get {
                return ResourceManager.GetString("bt_logPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически скопировать логин, затем пароль (Ctrl+D).
        /// </summary>
        public static string bt_logPass_tip {
            get {
                return ResourceManager.GetString("bt_logPass_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string bt_save {
            get {
                return ResourceManager.GetString("bt_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохр. с текущим паролем.
        /// </summary>
        public static string bt_saveWithCurrentPassword {
            get {
                return ResourceManager.GetString("bt_saveWithCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string bt_search {
            get {
                return ResourceManager.GetString("bt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск в таблице по заметкам и логинам (Ctrl+F).
        /// </summary>
        public static string bt_search_tip {
            get {
                return ResourceManager.GetString("bt_search_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторонние ресурсы.
        /// </summary>
        public static string bt_thirdPartyResources {
            get {
                return ResourceManager.GetString("bt_thirdPartyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string edit_confirm {
            get {
                return ResourceManager.GetString("edit_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставьте пустым для пропуска.
        /// </summary>
        public static string edit_leaveBlankToSkip {
            get {
                return ResourceManager.GetString("edit_leaveBlankToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной пароль.
        /// </summary>
        public static string edit_primaryPassword {
            get {
                return ResourceManager.GetString("edit_primaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл повреждён..
        /// </summary>
        public static string err_critical_fileDamaged {
            get {
                return ResourceManager.GetString("err_critical_fileDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот тип файла не поддерживается..
        /// </summary>
        public static string err_critical_fileNotSupported {
            get {
                return ResourceManager.GetString("err_critical_fileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критическая ошибка.
        /// </summary>
        public static string err_critical_title {
            get {
                return ResourceManager.GetString("err_critical_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот файл был создан в более поздней версии приложения и не может быть открыт. Обновите приложение..
        /// </summary>
        public static string err_critical_updateApp {
            get {
                return ResourceManager.GetString("err_critical_updateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоторые данные содержат недопустимые символы..
        /// </summary>
        public static string err_edit_dataInvalidChars {
            get {
                return ResourceManager.GetString("err_edit_dataInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись должна содержать заметку или логин с паролем..
        /// </summary>
        public static string err_edit_itemMustContain {
            get {
                return ResourceManager.GetString("err_edit_itemMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают..
        /// </summary>
        public static string err_edit_passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("err_edit_passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вероятно, эта ошибка вызвана использованием неподдерживаемого символа..
        /// </summary>
        public static string err_encryption_msg {
            get {
                return ResourceManager.GetString("err_encryption_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка шифрования.
        /// </summary>
        public static string err_encryption_title {
            get {
                return ResourceManager.GetString("err_encryption_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанное имя файла не поддерживается..
        /// </summary>
        public static string err_fileName_invalid {
            get {
                return ResourceManager.GetString("err_fileName_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла не должно начинаться с пробела..
        /// </summary>
        public static string err_fileName_spaceChar {
            get {
                return ResourceManager.GetString("err_fileName_spaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла слишком длинное..
        /// </summary>
        public static string err_fileName_tooLong {
            get {
                return ResourceManager.GetString("err_fileName_tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система Log&apos;n&apos;Pass в данный момент недоступна..
        /// </summary>
        public static string err_logPass_msg {
            get {
                return ResourceManager.GetString("err_logPass_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось открыть файл..
        /// </summary>
        public static string err_openFileFail {
            get {
                return ResourceManager.GetString("err_openFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной пароль не может быть пустым..
        /// </summary>
        public static string err_primaryPassword_empty {
            get {
                return ResourceManager.GetString("err_primaryPassword_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль..
        /// </summary>
        public static string err_primaryPassword_incorrect {
            get {
                return ResourceManager.GetString("err_primaryPassword_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной пароль содержит недопустимые символы. Разрешённые символы: .
        /// </summary>
        public static string err_primaryPassword_invalidChars {
            get {
                return ResourceManager.GetString("err_primaryPassword_invalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной пароль не может начинаться с косой черты..
        /// </summary>
        public static string err_primaryPassword_slashChar {
            get {
                return ResourceManager.GetString("err_primaryPassword_slashChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной пароль слишком длинный (макс. 32 символа)..
        /// </summary>
        public static string err_primaryPassword_tooLong {
            get {
                return ResourceManager.GetString("err_primaryPassword_tooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string err_title {
            get {
                return ResourceManager.GetString("err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение не имеет достаточных прав для записи данных в этот файл. Вам необходимо сохранить данные через &quot;Сохр. как&quot; в новый файл во избежание потери данных..
        /// </summary>
        public static string err_write_msg {
            get {
                return ResourceManager.GetString("err_write_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи.
        /// </summary>
        public static string err_write_title {
            get {
                return ResourceManager.GetString("err_write_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработал Максим Королев.
        /// </summary>
        public static string info_createdBy {
            get {
                return ResourceManager.GetString("info_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Система работает только с записями, которые содержат логин и пароль.
        ///• Система не работает в приложении Passtable.
        ///• По окончании работы буфер обмена будет очищен..
        /// </summary>
        public static string info_logPass_notes {
            get {
                return ResourceManager.GetString("info_logPass_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Выбрать запись в таблице;
        ///2. Нажать на кнопку &quot;Log&apos;n&apos;Pass&quot; (Ctrl+D);
        ///3. Перейти на форму авторизации (например, авторизация на сайте в браузере, ввод учетных данных в почтовом клиенте);
        ///4. Выбрать поле &quot;логин&quot; и нажать Ctrl+V;
        ///5. Затем выбрать поле &quot;пароль&quot; и нажать Ctrl+V;
        ///6. Готово..
        /// </summary>
        public static string info_logPass_steps {
            get {
                return ResourceManager.GetString("info_logPass_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как использовать систему &quot;Log&apos;n&apos;Pass&quot;.
        /// </summary>
        public static string info_logPass_title {
            get {
                return ResourceManager.GetString("info_logPass_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница проекта:.
        /// </summary>
        public static string info_projectPage {
            get {
                return ResourceManager.GetString("info_projectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий проекта:.
        /// </summary>
        public static string info_projectRepo {
            get {
                return ResourceManager.GetString("info_projectRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление содержит улучшения и исправления ошибок.
        /// </summary>
        public static string info_updateAvailable {
            get {
                return ResourceManager.GetString("info_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия:.
        /// </summary>
        public static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение для Windows.
        /// </summary>
        public static string info_winApp {
            get {
                return ResourceManager.GetString("info_winApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пробел.
        /// </summary>
        public static string key_space {
            get {
                return ResourceManager.GetString("key_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это действие не может быть отменено.
        /// </summary>
        public static string msg_permanentAction {
            get {
                return ResourceManager.GetString("msg_permanentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О приложении.
        /// </summary>
        public static string title_about {
            get {
                return ResourceManager.GetString("title_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись.
        /// </summary>
        public static string title_addEntry {
            get {
                return ResourceManager.GetString("title_addEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый файл.
        /// </summary>
        public static string title_createNewFile {
            get {
                return ResourceManager.GetString("title_createNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись?.
        /// </summary>
        public static string title_deleteEntry {
            get {
                return ResourceManager.GetString("title_deleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить запись.
        /// </summary>
        public static string title_editEntry {
            get {
                return ResourceManager.GetString("title_editEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметка.
        /// </summary>
        public static string title_note {
            get {
                return ResourceManager.GetString("title_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл.
        /// </summary>
        public static string title_openFile {
            get {
                return ResourceManager.GetString("title_openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string title_password {
            get {
                return ResourceManager.GetString("title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        public static string title_saveAs {
            get {
                return ResourceManager.GetString("title_saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метка.
        /// </summary>
        public static string title_tag {
            get {
                return ResourceManager.GetString("title_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление.
        /// </summary>
        public static string title_updateAvailable {
            get {
                return ResourceManager.GetString("title_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string title_username {
            get {
                return ResourceManager.GetString("title_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string toolbar_help {
            get {
                return ResourceManager.GetString("toolbar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горячие клавиши и информация о приложении (F1).
        /// </summary>
        public static string toolbar_help_tip {
            get {
                return ResourceManager.GetString("toolbar_help_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string toolbar_new {
            get {
                return ResourceManager.GetString("toolbar_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый файл (Ctrl+Shift+N).
        /// </summary>
        public static string toolbar_new_tip {
            get {
                return ResourceManager.GetString("toolbar_new_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string toolbar_open {
            get {
                return ResourceManager.GetString("toolbar_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл (Ctrl+O).
        /// </summary>
        public static string toolbar_open_tip {
            get {
                return ResourceManager.GetString("toolbar_open_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохр. как.
        /// </summary>
        public static string toolbar_saveAs {
            get {
                return ResourceManager.GetString("toolbar_saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения в другом файле с изменением основного пароля (Ctrl+Shift+S).
        /// </summary>
        public static string toolbar_saveAs_tip {
            get {
                return ResourceManager.GetString("toolbar_saveAs_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировано.
        /// </summary>
        public static string toolbar_status_copied {
            get {
                return ResourceManager.GetString("toolbar_status_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно данных.
        /// </summary>
        public static string toolbar_status_notEnoughData {
            get {
                return ResourceManager.GetString("toolbar_status_notEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не выбрано.
        /// </summary>
        public static string toolbar_status_nothingSelected {
            get {
                return ResourceManager.GetString("toolbar_status_nothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранено.
        /// </summary>
        public static string toolbar_status_saved {
            get {
                return ResourceManager.GetString("toolbar_status_saved", resourceCulture);
            }
        }
    }
}
